#!/usr/bin/env bash
#
# Build the in-browser Scala toolchain: the Scala 3 compiler and the Scala.js linker,
# cross-compiled with Scala.js and linked to WebAssembly.
#
# The upstream work lives in a research fork of dotty (see docs/research.md). We pin a
# commit, run its asset task, and lay the result out the way the engine expects.
#
# Usage:
#   scripts/build-compiler-assets.sh              # build (reuses the cached checkout)
#   FORK_REF=<sha> scripts/build-compiler-assets.sh
#   OUTPUT_DIR=... scripts/build-compiler-assets.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

FORK_URL="${FORK_URL:-https://github.com/pgilliar/scala3-compiler-sjs}"
FORK_REF="${FORK_REF:-357051c857d4ffd5d1e1bfc9a56f0cbf5943a325}"
CACHE_DIR="${CACHE_DIR:-$REPO_ROOT/.build-cache}"
CHECKOUT_DIR="${CHECKOUT_DIR:-$CACHE_DIR/scala3-compiler-sjs}"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/packages/playground/public/assets}"
SBT_OPTS="${SBT_OPTS:--Xmx10G -Xss8m -XX:MaxMetaspaceSize=1G}"
export SBT_OPTS

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

for tool in git java npm; do
  command -v "$tool" >/dev/null 2>&1 || die "missing required tool: $tool"
done
command -v sbt >/dev/null 2>&1 || die "missing sbt (https://www.scala-sbt.org/download)"

log "Toolchain source: $FORK_URL @ ${FORK_REF:0:12}"
if [[ "${SKIP_BUILD:-0}" == "1" ]]; then
  log "SKIP_BUILD=1: reusing the assets already present in $CHECKOUT_DIR"
elif [[ ! -d "$CHECKOUT_DIR/.git" ]]; then
  mkdir -p "$(dirname "$CHECKOUT_DIR")"
  log "Cloning (this fetches the full dotty history for the pinned commit)"
  git clone --filter=blob:none "$FORK_URL" "$CHECKOUT_DIR"
fi

if [[ "${SKIP_BUILD:-0}" != "1" ]]; then
  git -C "$CHECKOUT_DIR" fetch --filter=blob:none origin "$FORK_REF" 2>/dev/null ||
    git -C "$CHECKOUT_DIR" fetch --filter=blob:none origin
  git -C "$CHECKOUT_DIR" checkout --detach "$FORK_REF"

  log "Installing the build's Node dependency (jszip, used by the upstream task)"
  (cd "$CHECKOUT_DIR/compiler" && npm install --silent)

  log "Building the compiler bundle - expect 15-30 minutes on a cold cache"
  (cd "$CHECKOUT_DIR" && sbt -batch "scala3-compiler-sjs/prepareBrowserIDE")
fi

SOURCE_ASSETS="$CHECKOUT_DIR/compiler/browser-ide/assets"
[[ -f "$SOURCE_ASSETS/compiler/main.wasm" ]] || die "build did not produce main.wasm"

log "Staging assets into $OUTPUT_DIR"
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/compiler" "$OUTPUT_DIR/classpath" "$OUTPUT_DIR/runtime" "$OUTPUT_DIR/vendor"
cp "$SOURCE_ASSETS"/compiler/{main.wasm,main.js,__loader.js} "$OUTPUT_DIR/compiler/"
cp "$SOURCE_ASSETS"/classpath/rt.jar "$SOURCE_ASSETS"/classpath/scalajs-lib.jar "$OUTPUT_DIR/classpath/"
cp "$SOURCE_ASSETS"/runtime/runtime-sjsir.zip "$OUTPUT_DIR/runtime/"

# The compile-time Scala library must be `.class` + `.tasty`. The upstream task stages
# `scala-library-sjs/packageBin`, which on a clean build is the Scala.js *IR* jar (only
# `.sjsir`); a compiler given that jar cannot resolve `scala.Predef` and fails with
# "Not found: type Unit". Package the merged library class directory instead - the same
# one the upstream Node-hosted test uses.
SCALA_LIB_CLASSES="$CHECKOUT_DIR/compiler/target/scala3-compiler-sjs/node-libs/scala-lib"
[[ -d "$SCALA_LIB_CLASSES" ]] || die "missing $SCALA_LIB_CLASSES (run the sbt build first)"
grep -q . <<<"$(find "$SCALA_LIB_CLASSES" -name 'Predef.tasty' -print -quit)" ||
  die "$SCALA_LIB_CLASSES does not look like a Scala 3 library class directory"
jar --create --file "$OUTPUT_DIR/classpath/scala-lib.jar" -C "$SCALA_LIB_CLASSES" .

# The compiler bundle reads classpath jars through a hard-coded `../vendor/jszip-wrapper.js`
# import. Upstream satisfies that with a 370 KB vendored copy of JSZip; we satisfy it with
# our own reader over the platform's DecompressionStream instead.
ENGINE_SRC="$REPO_ROOT/packages/scala-engine/src"
cp "$ENGINE_SRC/jszip-compat.js" "$ENGINE_SRC/zip.js" "$OUTPUT_DIR/vendor/"
cat > "$OUTPUT_DIR/vendor/jszip-wrapper.js" <<'WRAPPER'
// Generated by scripts/build-compiler-assets.sh - see packages/scala-engine/src/jszip-compat.js
export { default } from "./jszip-compat.js";
WRAPPER

cat > "$OUTPUT_DIR/manifest.json" <<JSON
{
  "toolchain": {
    "source": "$FORK_URL",
    "ref": "$FORK_REF",
    "builtAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  },
  "compilerModule": "./compiler/main.js",
  "runtimeIR": "./runtime/runtime-sjsir.zip",
  "classpath": [
    { "path": "/lib/rt.jar", "url": "./classpath/rt.jar" },
    { "path": "/lib/scala-lib.jar", "url": "./classpath/scala-lib.jar" },
    { "path": "/lib/scalajs-lib.jar", "url": "./classpath/scalajs-lib.jar" }
  ]
}
JSON

log "Done. Payload:"
du -ch "$OUTPUT_DIR"/compiler/* "$OUTPUT_DIR"/classpath/* "$OUTPUT_DIR"/runtime/* | sort -h
if command -v brotli >/dev/null 2>&1; then
  log "Compressed size of main.wasm (brotli -q 5): $(brotli -q 5 -c "$OUTPUT_DIR/compiler/main.wasm" | wc -c | numfmt --to=iec)"
fi
